// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyczbbdmtyqgmautsibg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y3piYmRtdHlxZ21hdXRzaWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjYxMjcsImV4cCI6MjA3MTg0MjEyN30.uGgC_7td2p6hN6hJBI4moBWuAwwP5qAcEjo3vtdIEy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});